name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # This ensures the GitHub runner downloads the real PDFs

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs push --all https://munichpavel:$HF_TOKEN@huggingface.co/spaces/munichpavel/ai-ready-data main
          git push -f https://munichpavel:$HF_TOKEN@huggingface.co/spaces/munichpavel/ai-ready-data main